name: fdh_tutorial_cv_dl
channels:
  - defaults
  - menpo
dependencies:
  - imageio=2.4
  - jupyter=1.0
  - matplotlib=3.0
  - numpy=1.15
  - pillow=5.2
  - python=3.5
  - scikit-image=0.14
  - scikit-learn=0.20
  - scipy=1.1
  - tensorflow=1.13
  - tqdm=4.36
  - dlib=19.9
